# serverless.yml

service: pp-serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# you can add packaging information here
package:
  patterns:
    - '!venv/**'
    - '!node_modules/**'
    - app.py
    - 'requirements.txt'
    - '!.serverless/**'